docs: First draft for updated readme
single-cell-data/TileDB-SOMA pull request #1069
Opened 2023-03-08 06:12 UTC by pablo-gar

**Issue and/or context:**
Adressed #1021 and #1020 

**Notes for Reviewer:**

- Please review redaction, technical accuracy, and contents.

2023-03-09 03:09 UTC, pablo-gar commented
@johnkerl please feel free to add any other reviewers that you may deem necessary

2023-03-10 20:59 UTC, aaronwolen approved these changes
Very nice! I made a couple of suggestions but this is a nice improvement.

2023-03-10 20:59 UTC, aaronwolen commented on README.md
> +* Load and create [Seurat](https://anndata.readthedocs.io/en/latest/) objects. *Coming soon*.
``
```suggestion
* Load and create [Seurat](https://satijalab.org/seurat/) objects. *Coming soon*.
```

2023-03-10 20:59 UTC, aaronwolen commented on README.md
> +* From R create RArrow objects, Matrix sparse matrices, and R-base dense matrices.
```suggestion
* From R create R Arrow objects, sparse matrices (via the [Matrix](https://cran.r-project.org/package=Matrix) package), and standard data frames and (dense) matrices.
```

2023-03-10 20:59 UTC, aaronwolen commented on README.md
> +	* `ms`: a  `Collection` of measurements, each composed of `X` matrices and axis annotation matrices or data frames.
Let's add periods to all bullets or none

2023-03-10 21:01 UTC, thetorpedodog reviewed
I have no comment on the contents themselves, just some formatting and link issues.

It might also be worth running through prettier to ensure everything is formatted uniformly, like in https://github.com/single-cell-data/SOMA/pull/134.

2023-03-10 21:05 UTC, ebezzi commented on README.md
> +* R [documentation](#tiledb-soma) | [tutorials](#tiledb-soma). *Under development*.
I think they're supposed to link to the docpages that do not exist yet.

2023-03-10 21:12 UTC, ebezzi commented on README.md
> +* `DenseNDArray` a dense, N-dimensional array, with offset (zero-based) integer indexing on each dimension.
```suggestion
* `DenseNDArray` is a dense, N-dimensional array, with offset (zero-based) integer indexing on each dimension.
```

2023-03-10 21:12 UTC, ebezzi commented on README.md
> +* `SparseNDArray` same as `DenseNDArray` but sparse, and it supports point indexing (disjoint index access)
```suggestion
* `SparseNDArray` is the same as `DenseNDArray` but sparse, and supports point indexing (disjoint index access)
```

2023-03-10 21:12 UTC, ebezzi commented on README.md
> +* `DataFrame`  a multi-column table with a user-defined columns names and value types, with support for point indexing.
```suggestion
* `DataFrame` is a multi-column table with a user-defined columns names and value types, with support for point indexing. 
```

2023-03-10 21:12 UTC, ebezzi commented on README.md
> +* `Collection` a persistent container of named SOMA objects.
```suggestion
* `Collection` is a persistent container of named SOMA objects.
```

2023-03-11 18:20 UTC, bkmartinjr reviewed
Suggest adding a section linking back to user's of the package, i.e., "Who is using SOMA", and linking back to Cell Census and other user's who are OK with a public statement of support

2023-03-13 16:51 UTC, pablo-gar commented on README.md
> +* R [documentation](#tiledb-soma) | [tutorials](#tiledb-soma). *Under development*.
Indeed will update once this is ready

2023-03-13 16:52 UTC, pablo-gar commented on README.md
> +TiledDB-SOMA provides interoperability with existing single-cell toolkits:
Thanks!

2023-03-13 16:52 UTC, pablo-gar commented on README.md
> +* Load and create [Seurat](https://anndata.readthedocs.io/en/latest/) objects. *Coming soon*.
fixed

2023-03-13 19:01 UTC, johnkerl requested changes

2023-03-13 19:01 UTC, johnkerl commented on README.md
> +* Python [documentation](https://tiledbsoma.readthedocs.io/en/latest/python-api.html) | [tutorials](#tiledb-soma) *Coming soon* .
please rebase atop #1103

2023-03-13 19:13 UTC, johnkerl requested changes

2023-03-13 19:13 UTC, johnkerl commented on README.md
> +* Python [documentation](https://tiledbsoma.readthedocs.io/en/latest/python-api.html) | [tutorials](#tiledb-soma) (*Coming soon*).
```suggestion
* Python [documentation](https://tiledbsoma.readthedocs.io/en/latest/python-api.html) | [tutorials](#tiledb-soma)
```

this is no longer "coming soon". it is already live.

2023-03-13 19:13 UTC, johnkerl commented on README.md
> +* R [documentation](https://single-cell-data.github.io/TileDB-SOMA/) | [tutorials](#tiledb-soma) (*Coming soon*).
```suggestion
* R [documentation](https://single-cell-data.github.io/TileDB-SOMA/) | [tutorials](#tiledb-soma).
```

this is no longer "coming soon". it is already live.

2023-03-13 19:23 UTC, johnkerl requested changes

2023-03-13 19:23 UTC, johnkerl commented on README.md
> +* R [documentation](https://single-cell-data.github.io/TileDB-SOMA/) | [tutorials](#tiledb-soma).
```suggestion
* Python [documentation](https://tiledbsoma.readthedocs.io/en/latest/python-api.html). 
* R [documentation](https://single-cell-data.github.io/TileDB-SOMA/).
```

Per our Slack sync :)

2023-03-13 19:25 UTC, johnkerl approved these changes

2023-03-13 19:26 UTC, merged