Switching to pandas2 in setup.py.
single-cell-data/TileDB-SOMA pull request #1217
Opened 2023-04-04 22:02 UTC by beroy

Note that this change by itself may not be sufficient as most of our usecases is in the form of arrow table.concact.to_pandas() I tried to use `pd.set_option("mode.dtype_backend", "pyarrow")` but was not able to get the same effect and als to_pandas(...) does not have the dtype argument like some of the pandas methods.

**Issue and/or context:1124

**Changes:Updating pandas version

**Notes for Reviewer:**

2023-04-04 23:38 UTC, atolopko-czi requested changes
Let's try the official `2.0.0` version instead of the `rc0`. Looks like that's what causing the build failure as well.

2023-04-05 00:11 UTC, beroy commented
Too strange! I don't get that error locally.

2023-04-05 14:03 UTC, atolopko-czi commented
So when pandas2 is an explicit requirement of TileDB-SOMA, is pyarrow's `to_pandas()` returning a PyArrow-backed Pandas DataFrame? E.g., when executing `a_soma_dataframe.read().concat().to_pandas().  Since this "zero-copy" DataFrame instantiation is one of main benefits of the Pandas2 upgrade (https://datapythonista.me/blog/pandas-20-and-the-arrow-revolution-part-i), it's worth understanding what's happening in practice.

I think we'll also need to upgrade SOMA (the core repo) to use pandas2.

After doing a local install of TileDB-SOMA (via make install), what version of pandas does `pip list` report?

2023-04-10 16:15 UTC, beroy commented
Same error with 2.0.0

2023-04-11 17:56 UTC, beroy commented
```pip list
packaging           23.0
pandas              2.0.0
patsy               0.5.3
Pillow              9.4.0
pip                 22.3.1
pipdeptree          2.7.0
pluggy              1.0.0
pyarrow             11.0.0
pybind11-global     2.10.4
```

2023-04-11 17:58 UTC, beroy commented
Should we try to build pyarrow with panda2?

2023-04-24 16:23 UTC, beroy commented
The main finding here is using panda 2.0 will not much affect the current TileDB-SOMA code. However, given that the main use case of panda 2.0 in TileDB-SOMA happens through arrow and current build of arrow is not using panda 2.0 it can affect TileDB-SOMA when arrow uses panda 2.0 in the future. One possible next step is to build arrow with panda 2.0 and try that on TileDB-SOMA.

2023-04-24 16:23 UTC, closed without merging