[c++] Rework `SOMAArray` Reader Iterator Sequence
single-cell-data/TileDB-SOMA pull request #1749
Opened 2023-09-30 04:37 UTC by nguyenv

**Issue and/or context:**

#1744

**Changes:**

- Do not submit query until `read_next()` is called
- Remove `SOMAArray::submit()`

**Notes for Reviewer:**

- Working but want to rename functions and clean up code

2023-10-02 17:24 UTC, eddelbuettel requested changes

2023-10-02 17:24 UTC, eddelbuettel commented on .github/workflows/r-ci.yml
> +        if: failure()
Please restore the Coverage option.

2023-10-02 20:44 UTC, eddelbuettel approved these changes
Nice work!

2023-10-03 16:44 UTC, johnkerl approved these changes

2023-10-03 16:51 UTC, merged