[c++] Modify `ManagedQuery` to perform async queries
single-cell-data/TileDB-SOMA pull request #1953
Opened 2023-12-05 22:07 UTC by nguyenv

**Issue and/or context:**

Across both APIs we have observed the `SOMAArray` intermittenly segfault when accessing the array. This occurs due to a race condition where we have multiple read queries and one query closes the array before the other queries have completed. When a query that has not completed tries to access a closed array, it segfaults. The solution is to modify the C++ `ManagedQuery` so that it performs async queries and waits for all query threads to complete before closing the `SOMAArray`.

**Changes:**

- Changes pulled from #1817

2023-12-05 22:11 UTC, eddelbuettel reviewed
LGTM but I am not very deep into `std::future<>` so merely commenting for now.  

I am also a little fuzzy about when we actually launch multiple queries at once -- I had the (wrong, clearly) mental model that we launch one, and iterate if its status is incomplete.

2023-12-05 22:13 UTC, johnkerl requested changes
This needs to be branched off `main` and then we can backport to `release-1.6`

At present it's branched off @mojaveazure 's feature-dev work which is unrelated to, and should not block, the 1.6.0 release we're trying to get out today

2023-12-05 22:15 UTC, johnkerl commented
Meanwhile @nguyenv  I really appreciate the debug, and am verifying it on #1943 -- which I will rebase later once this is merged to `release-1.6` -- so #1943 will go back to being only `apis/r/DESCRIPTION` and `apis/r/NEWS.md`

2023-12-05 22:15 UTC, eddelbuettel commented
Good catch @johnkerl -- I only saw 'one commit' and nodded and was asleep as to the branch it came from.

2023-12-05 22:38 UTC, gspowley approved these changes
LGTM! One minor suggestion.

2023-12-05 22:38 UTC, gspowley commented on libtiledbsoma/src/soma/managed_query.cc
> +    query_future_.wait();
We should check if the `query_future_` is valid like we do in `ManagedQuery::close()`. 

Something like this:
```c++
if (query_future_.valid()) {
    LOG_DEBUG(fmt::format("[ManagedQuery] [{}] Waiting for query", name_));
    query_future_.wait();
} else {
    // throw error
}
```

We expect it to be valid, but it's good to check.

2023-12-06 00:24 UTC, johnkerl approved these changes

2023-12-06 00:25 UTC, merged