[python,c++][wip] Use C++ DenseNDArray bindings in Python API
single-cell-data/TileDB-SOMA pull request #2494
Opened 2024-04-29 17:00 UTC by nguyenv

**Issue and/or context:**

**Changes:**

**Notes for Reviewer:**

2024-04-30 03:27 UTC, nguyenv commented on apis/python/src/tiledbsoma/io/ingest.py
> +        matrix = sp.csr_matrix(matrix)
This is a workaround for getting CSC matrices to write properly with the new `clib.DenseNDArray` bindings. I would appreciate it if someone could suggest a better solution.

2024-04-30 14:37 UTC, johnkerl requested changes
https://github.com/single-cell-data/TileDB-SOMA/pull/2494#discussion_r1584926419

2024-05-01 14:39 UTC, nguyenv commented on apis/python/src/tiledbsoma/io/ingest.py
> +        matrix = sp.csr_matrix(matrix)
Thank you so much @johnkerl! This is extremely helpful, and I really appreciate it. I couldn't figure it out after a weekend of debugging.

2024-05-02 12:46 UTC, johnkerl approved these changes
🚢 
Awesome @nguyenv !! :)

2024-05-06 20:57 UTC, merged