[r] Fix dependency of a test on fixed buffer sizes [WIP]
single-cell-data/TileDB-SOMA pull request #2685
Opened 2024-06-05 17:30 UTC by johnkerl

Addresses #2684 

Something's not quite right here -- the requested `soma.init_buffer_bytes` isn't making it all the way to `column_buffer.cc`

* In our repo CI we have `export TILEDB_SOMA_INIT_BUFFER_BYTES=16777216`
* In the nightlies https://github.com/jdblischak/centralized-tiledb-nightlies/issues/11#issuecomment-2150323719 we do not
* On my laptop I do not
* If I set `export TILEDB_SOMA_INIT_BUFFER_BYTES=16777216` then the `tests/testthat/test-SOMAArrayReader-Iterated.R"` tests pass
* Using the `ctx <- SOMATileDBContext$new(c(soma.init_buffer_bytes='16777216'))` logic on this PR they do not pass
* Therefore I don't see that the desired buffer size is reaching all the way to `column_buffer.cc`

2024-06-05 20:38 UTC, jdblischak commented
I kicked off a nightly run that uses [kerl/flex-buffer-sizes](https://github.com/single-cell-data/TileDB-SOMA/tree/kerl/flex-buffer-sizes) for TileDB-SOMA

https://github.com/jdblischak/centralized-tiledb-nightlies/actions/runs/9390901834

2024-06-05 20:43 UTC, mojaveazure approved these changes
LGTM
![image](https://github.com/single-cell-data/TileDB-SOMA/assets/11035068/1badcb66-3287-427c-8390-ae9a78527665)

2024-06-05 21:03 UTC, eddelbuettel commented on apis/r/vignettes/soma-experiment-queries.Rmd
> +To use larger (or smaller) buffer sizes:
Maybe mention the environment variable setter as the usual fallback (as we are going to Core code here) ?

2024-06-05 21:04 UTC, eddelbuettel commented on apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
> +                      sparse = SOMASparseNDArrayOpen(uri, tiledbsoma_ctx = ctx))
Switch to factory method is good, the test was likely written before we added these.

In the interim @mojaveazure and I had huddled too and see that the create step has the entry for a ctx object so this seems like the best approach.

2024-06-05 21:05 UTC, eddelbuettel requested changes
Please also remove the now no-longer needed env variable from the CI yaml files.

2024-06-05 21:08 UTC, johnkerl commented
@eddelbuettel as discussed in https://github.com/single-cell-data/TileDB-SOMA/pull/2681 I had on #531 attempted this before and ran into issues with various-sized runners.

The `TILEDB_SOMA_INIT_BUFFER_BYTES` lines on the current CI YAMLs are for robustness with respect to various GHA runners.

They are not related to the bugfix done on this PR.

This PR fixed a bug wherein two cases would pass only with fixed buffer sizes. That is fixed.

What remains, and what needs to remain, is "low ceiling" for all tests, all languages (Python and R), Linux, MacOS, and Windows.

2024-06-05 21:26 UTC, merged

2024-06-05 22:36 UTC, eddelbuettel commented
> The TILEDB_SOMA_INIT_BUFFER_BYTES lines on the current CI YAMLs are for robustness with respect to various GHA runners.
> 
> They are not related to the bugfix done on this PR.

By keeping them as env vars you ensure the values are picked up. That neuters any and all CI on this very PR.  As the values are already picked 'for certain' from the TileDB Core API under this, we cannot actually ascertain that this PR does as it claims.

2024-06-05 22:43 UTC, johnkerl commented
@eddelbuettel thank you for your feedback.

As noted I don't want to break future CI including Windows as linked on #531.

And we do have the nightlies.

The env vars here must be retained.

But I could bump them from say 16MB in the env vars to 32MB, to ensure bug-fix regression checking on `apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R` _and_ maintaining the "low ceiling" needed for Windows CI.

2024-06-05 22:47 UTC, eddelbuettel commented
Conceptually speaking, now that have a handle on setting size as needed, should we not run with the defaults at CI (because hey, CI is there to check our defaults) and the override in test files as needed as we did here?   

(I am aware that we are smudging the lines in other places by suppressing some CI tests on some platforms, or under valgrind, or skip some, ... )

2024-06-05 22:54 UTC, johnkerl commented
This is a good idea.

2024-06-05 22:57 UTC, eddelbuettel commented
That's basically what I wanted to get at with 'remove the CI value' because it will not blind us from possible errors outside of CI (i.e. real users and clients...) as we are forcing the old small size back in.  Maybe worth a try in a branch.

The main thing is that the regression is fixed, and Paul and I had some good chats about configs. All that may need a revisit too.

2024-06-05 22:57 UTC, johnkerl commented
I will file a follow-up task.

There is other more pressing tech debt than this.

Thank you for your dialogue.

2024-06-05 23:00 UTC, eddelbuettel commented
I maintained for maybe one and a half years that the layout, build system and CI are all tech debt and got some verbal promises that 'after the release (i.e 1.5.0) this would get addressed.  But that's the way it goes with promises: some remain unfulfilled.

2024-06-05 23:50 UTC, johnkerl commented
Getting rid of TileDB-Py and TileDB-R remains tech debt number one. Glad we're getting close on those.

2024-06-06 00:49 UTC, eddelbuettel commented
Well we will see about that.  All the config calls we used today make use of tiledb-r config and ctx objects.