[c++] Create helper function for casting bits to uint8
single-cell-data/TileDB-SOMA pull request #2764
Opened 2024-07-01 15:30 UTC by nguyenv

Avoid duplicating code by creating helper function `_cast_bit_to_uint8`

2024-07-01 15:33 UTC, johnkerl requested changes
Did you perhaps forget to `git add` the file implementing `_cast_bit_to_uint8`? I don't see it ...

2024-07-01 15:33 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_array.h
> +    // Help function to cast Boolean of bits (Arrow) to uint8 (TileDB)
```suggestion
    // Helper function to cast Boolean of bits (Arrow) to uint8 (TileDB)
```

2024-07-01 15:46 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_array.cc
> +            casted.push_back((uint8_t)((byte >> j) & 0x01));
It's easy (in my years of doing things like this) to get the bit-ordering backward.

Let's make sure we have focused unit-test coverage in `libtiledbsoma/test/unit_*.cc`

2024-07-15 16:25 UTC, nguyenv commented
Included in #2786.

2024-07-15 16:25 UTC, closed without merging