[python] Skip tests that use tiledb-py if not installed
single-cell-data/TileDB-SOMA pull request #2883
Opened 2024-08-12 22:54 UTC by nguyenv

**Issue and/or context:**

This PR is separated out from https://github.com/single-cell-data/TileDB-SOMA/pull/2752

**Changes:**

Skip tests that use tiledb-py if not installed

2024-08-12 23:03 UTC, johnkerl requested changes
@nguyenv thanks!!!

I'm putting this as request-changes just to put a "hold" on it -- no indication anything's necessarily wrong but rather to flag some things for conversation:

* Will we be doing pip-install of tiledb-py within our CI jobs?
  * If so: may need some (light) handling around core versions in the case when
    * Core has bumped storage-format version
    * TileDB-Py has that new core available at PyPI and TileDB-SOMA Py does not (or vice versa)
  * Also if so: that means the tests you have here may go "uncovered" for a while until we restore pip-install of tiledb-py within our CI YAML -- ok as long as we understand/track what we're doing
  * If not:
    * We'll be losing test coverage of assertions we once made and now no longer can
    * How bad is this??

Since the core C++ API (and C API) are "full APIs" that means anything we can/do do in TileDB-Py we should be able to do ourselves -- I want us to at least have the _conversation_ about what to do with things like

```
            assert A.schema.sparse
            assert not A.schema.allows_duplicates
            assert A.dim("foo").filters == [tiledb.ZstdFilter(level=3)]
            assert A.attr("bar").filters == [tiledb.ZstdFilter()]
```

-- namely: can we either:

* Expose some of these things via `libtiledbsoma` -> `pybind11`/`Rcpp` -> `tiledbsoma-py`/`tiledbsoma-r` -> so we can still test them at the `pytest` level?
* Or, maybe expose something only at the `libtiledbsoma` level (no bindings) and then move these test cases from `pytest` (or `testthat` for R) to `ctest` for `libtiledbsoma`

2024-08-13 20:15 UTC, nguyenv commented
My idea for the latter conerns: When creating a `SOMAArray` in C++, we can store the `PlatformConfig` that's passed in to generate the `ArraySchema`. Then have a `platform_config` getter that we can bind in the APIs. In Python, we could return that as a JSON formatted string.

2024-08-13 20:24 UTC, nguyenv commented
I think we should install tiledb-py when running CI. We could have a `requirements_ci.txt` that pulls everything from `requirements_dev.txt` with just the additional requirement for `tiledb`. But yes we'd have to make sure the version of tiledb-py it pulls is compatible with the libtiledbsoma in tiledbsoma-py. I don't know how to deal with that yet but can look into it.

2024-08-13 20:28 UTC, johnkerl commented
> My idea for the latter conerns: When creating a SOMAArray in C++, we can store the PlatformConfig that's passed in to generate the ArraySchema. Then have a platform_config getter that we can bind in the APIs. In Python, we could return that as a JSON formatted string.
> 
> So essentially your first bullet point.

Hmm, I hadn't thought of that. TBH I don't think this is a good check -- it will be checking a copy of platform config stored somewhere, not checking against readback of the actual core schema that was created. We need to actually read the core schema and do these checks -- if we want to continue doing them at all ...

2024-10-15 20:19 UTC, nguyenv commented
All changes in this branch have been split out into multiple PRs and merged into main.

2024-10-15 20:19 UTC, closed without merging