[r] [WIP] Add support for reading v5 assays from an axis query
single-cell-data/TileDB-SOMA pull request #3008
Opened 2024-09-17 18:01 UTC by mojaveazure

Seurat v5 adds support for ragged arrays, where not every `X` layer has exactly the same cells and features. To handle this, ragged `X` layers need to be re-indexed and re-shaped on ingestion to resize down to only the data present

Modified SOMA methods:
 - `SOMAExperimentAxisQuery$to_seurat()` and `SOMAExperimentAxisQuery$to_seurat_assay()`: now read in as v5 assays

New SOMA methods:
 - `SOMAExperimentAxisQuery$private$.to_seurat_assay_v5()`: helper method to read in ragged and non-ragged arrays into a v5 assay; note this method only handles expression layers, all other assay-level information is handled by parent `$to_seurat_assay()` to share code with v3 assay outgestion

Requires #2523 and #3007

[SC-52261](https://app.shortcut.com/tiledb-inc/story/52261/)

2024-11-07 15:39 UTC, johnkerl requested changes
Notes from initial readability pass

2024-11-07 15:39 UTC, johnkerl commented on apis/r/R/SOMAExperimentAxisQuery.R
> +      # Get the assay version
```suggestion
      # Get the Seurat assay version
```

2024-11-07 15:39 UTC, johnkerl commented on apis/r/R/SOMAExperimentAxisQuery.R
> +      lname <- SeuratObject::RandomName(length = 7L)
```suggestion
      layer_name <- SeuratObject::RandomName(length = 7L)
```

2024-11-07 15:39 UTC, johnkerl commented on apis/r/R/SOMAExperimentAxisQuery.R
> +      for (lyr in layers) {
```suggestion
      for (layer_name in layer_names) {
```

2024-11-07 15:39 UTC, johnkerl commented on apis/r/R/SOMAExperimentAxisQuery.R
> +        lcells <- cells
```suggestion
        layer_cells <- cells
```

2024-11-07 15:39 UTC, johnkerl commented on apis/r/R/SOMAExperimentAxisQuery.R
> +        lfeatures <- features
```suggestion
        layer_features <- features
```

2024-11-07 15:39 UTC, johnkerl commented on apis/r/R/SOMAExperimentAxisQuery.R
> +          sdx <- vector("list", length = length(dnames))
I have no idea what `sdx` means. Please use a longer name that indicates what this means.

2024-11-07 15:39 UTC, johnkerl commented on apis/r/tests/testthat/helper-test-soma-objects.R
> +  nd <- seq(from = 0L, to = 1L, by = 0.1)
`nd` = number of dimensions? Please spell out with an informative name.

2025-01-17 22:04 UTC, mojaveazure commented on apis/r/R/SOMAExperimentAxisQuery.R
> +      for (lyr in layers) {
Skipping this as the I've applied the `lname` &rarr; `layer_name` suggestion above. Changing here will overwrite the `layer_name` variable defined above, and I still need said `layer_name` (which is why I originally used `lname` and `lyr` as it kept the two uses separate)

2025-04-08 16:49 UTC, johnkerl approved these changes
🚢

2025-04-08 16:51 UTC, merged