[r] Port query-condition logic from TileDB-R to TileDB-SOMA-R [WIP]
single-cell-data/TileDB-SOMA pull request #3162
Opened 2024-10-10 19:21 UTC by johnkerl

**Issue and/or context:** #3051 

**Changes:**

**Notes for Reviewer:**

This PR is not ready for review.

2024-10-10 22:39 UTC, johnkerl commented on apis/r/tests/testthat/test-query-condition.R
> +          # XXX FIXME
@mojaveazure I'm having a hard time reading back factors and checking them against expected values. More in Slack if you like.

2024-10-10 22:39 UTC, johnkerl commented on apis/r/tests/testthat/test-query-condition.R
> +          # expect_equal(df$enum, c("green"))
@mojaveazure I'm having a hard time reading back factors and checking them against expected values. More in Slack if you like.

2024-10-10 23:04 UTC, johnkerl commented on apis/r/tests/testthat/test-query-condition.R
> +          # expect_equal(df$enum, c("green"))
Resolved thanks to @mojaveazure: 

```
expect_equal(as.character(df$enum), c("green"))
```

2024-10-15 16:03 UTC, mojaveazure requested changes

2024-10-15 16:03 UTC, mojaveazure commented on apis/r/R/QueryCondition.R
> +parse_query_condition_new <- function(
Keep this internal to make it easier to re-build/re-write at a later date
```suggestion
#' @return A `tiledbsoma_query_condition` object.
#' 
#' @noRd
#'
parse_query_condition_new <- function(
```

2024-10-15 16:03 UTC, mojaveazure commented on apis/r/R/QueryCondition.R
> +#' @exportClass tiledbsoma_query_condition
This S4 class doesn't need to be exported
```suggestion
```

2024-10-15 16:03 UTC, mojaveazure commented on apis/r/R/QueryCondition.R
> +tiledbsoma_query_condition_from_triple <- function(
Keep this internal to make it easier to re-build/re-write at a later date
```suggestion
#' @return The initialized 'tiledbsoma_query_condition' object
#' 
#' @noRd
#'
tiledbsoma_query_condition_from_triple <- function(
```

2024-10-15 16:03 UTC, mojaveazure commented on apis/r/R/QueryCondition.R
> +tiledbsoma_query_condition_combine <- function(lhs, rhs, op_name, somactx) {
```suggestion
#' @return The combined 'tiledbsoma_query_condition' object
#' 
#' @noRd
#'
tiledbsoma_query_condition_combine <- function(lhs, rhs, op_name, somactx) {
```

2024-10-15 16:03 UTC, mojaveazure commented on apis/r/R/QueryCondition.R
> +tiledbsoma_query_condition_in_nin <- function(
```suggestion
#' @return A query-condition object is returned
#' 
#' @noRd
#'
tiledbsoma_query_condition_in_nin <- function(
```

2024-10-15 17:10 UTC, nguyenv commented on apis/r/tests/testthat/test-query-condition.R
> +test_that("DataFrame Factory", {
Some other cases I can think of:
- Mismatched types like `soma_joinid == "ten"`
- What is the behavior for comparing floats and strings like `soma_joinid == 10.0`?
- What is the behavior for overflow/underflow  `int8== 100000000`? 
- Comparing signed and unsigned `int8 == -1`
- Make sure parens evaluate correctly
- Incomplete query conditions: `soma_joinid ==`, `soma_joinid && int8`, `soma_joinid == 1 &&` 

Could potentially do this on a follow-up PR.

2024-10-15 18:56 UTC, mojaveazure approved these changes
LGTM; please bump the develop version, update the changelog, and 🚢

2024-10-15 19:38 UTC, merged