[r] Run `styler::style_pkg()`
single-cell-data/TileDB-SOMA pull request #3239
Opened 2024-10-25 14:04 UTC by johnkerl

Fully automated

2024-10-28 15:06 UTC, mojaveazure requested changes

2024-10-28 22:05 UTC, johnkerl commented on apis/r/R/BlockwiseIter.R
> +                          reindex_disable_on_axis = NA) {
Changes as discussed 1-1

2024-10-29 18:14 UTC, mojaveazure requested changes

2024-10-29 18:56 UTC, mojaveazure approved these changes
I've manually fixed the incorrect indentations; assuming tests pass this is ready to 🚢

2024-10-29 19:12 UTC, merged