[c++] SOMAColumn
single-cell-data/TileDB-SOMA pull request #3329
Opened 2024-11-18 11:42 UTC by XanthosXanthopoulos

`SOMAColumn` provides an abstraction over TileDB attributes and dimensions and exposes a common interface for all columns regardless of type. Subclasses of `SOMAColumn` can implement complex indexing mechanism through additional dimensions and encapsulate all that logic in one place and make it modular. 

Subsequent PRs will add implementation for dimension and attributes.

2024-11-18 17:09 UTC, jp-dark approved these changes

2024-11-18 17:09 UTC, jp-dark commented on libtiledbsoma/src/soma/soma_column.h
> +     * @param ranges
These don't match the function template parameter/parameter names.

2024-11-18 23:14 UTC, johnkerl requested changes
This looks like interesting work but it's not clear why it's being done.

You need a GitHub issue, or Shortcut link, in the description field.

From your GitHub branch name I can discover a Shortcut story number -- since this is an open-source project, please include within a GitHub issue the context that is necessary for anyone who is not a TileDB employee to understand what changes you're making here, and why.

This PR introduces new code without any unit tests, and no callsite from existing code that would exercise existing unit tests. It could be stamped now with guarantee of unit-test cases to follow, but, I'd be happier if you could offer at least a minimal set of tests.

2024-11-18 23:14 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_column.h
> + *   This file defines the SOMAColumn class.
Please say what this class is for, what problem it solves. This comment, as is, doesn't tell anything that `class SOMAColuimn { ... }` doesn't.

In particular, up until there's been a 1-1 mapping of one soma column -> one tiledb dim or one tiledb attr. Here it appears (I'm still reading but it appears so far) that you are allowing for one-to-many mappings of one soma column -> more than one tiledb dim and/or more than one tiledb attr. A top-of-file comment here would need to explain this in at least several sentences' worth of detail.

2024-11-18 23:14 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_column.h
> +     * `if_not_empty` parameter is `true`, the column will be selected iff the
"iff" is specialist mathematical jargon that non-mathematicians are unlikely to recognize. Please don't use it.

2024-11-18 23:14 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_column.h
> +     * @param if_not_empty Prevent changing an "empty" selection of all columns
```suggestion
     * @param if_not_empty Prevent changing an empty selection of all columns
```

2024-11-20 00:16 UTC, nguyenv commented on libtiledbsoma/src/soma/soma_column.h
> +     * else false.  Note that this only should be used if the SOMACOlumn objects
```suggestion
     * @brief Returns true if the SOMAColumn has a non-empty current domain,
     * else false.  Note that this only should be used if the SOMAColumn objects
```

2024-11-20 00:16 UTC, nguyenv commented on libtiledbsoma/src/soma/soma_column.h
> +        : ctx(ctx){};
Should we take in a `tiledb::Context` or `SOMAContext`?

2024-12-12 11:17 UTC, XanthosXanthopoulos commented
This PR has been split into #3424 , #3425 , #3426 and #3427.

2024-12-12 11:17 UTC, closed without merging