Integrate `SOMAColumn` in Arrow adapter methods [WIP]
single-cell-data/TileDB-SOMA pull request #3405
Opened 2024-12-06 15:21 UTC by XanthosXanthopoulos

**Issue and/or context:**

**Changes:**

**Notes for Reviewer:**

2024-12-09 19:14 UTC, nguyenv reviewed
Can you explain what the `Skip` and `Take` are for and document it? It looks like `Take` is the index of the column to retrieve and `Skip` is relevant only for geometry columns (where it's always 2)?

Also is there a way to use `std::variant` or a templated type instead of `std::any` or would that make things too complicated?

2024-12-10 09:11 UTC, XanthosXanthopoulos commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     */
`Skip` and `Take` are used in 2 places with 2 specific sets on values (either `Skip=3` and `Take=2` or `Skip=0` and `Take=2`) and are independent of the geometry column. Their usage is to extract specific subranges of ArrowArray data and they come in handy during `ArrowSchema -> TileDBSchema` where the arrow array provided has 5 values per dimension and we only need the last 2 to set the current domain.

As to using `std::variant`, adding more `SOMAColumn` types would require changing multiple variants. The use of `std::any` here is to enable runtime polymorphism and indirectly introduces a runtime type check (via `any_cast`, `make_any`) between the templated function and the actual dimension type. `std::variant` can provide all the above it is just a different style I am open to discuss further.

2025-01-15 16:21 UTC, jp-dark commented on libtiledbsoma/src/utils/arrow_adapter.h
> +    static std::vector<std::array<T, Take>> get_table_column_by_name(
This doesn't appear to be used anywhere. Can you pull it out into a separate PR and/or add it to the branch where it is used?

2025-01-15 20:14 UTC, jp-dark reviewed
I didn't review the `get_table_column_by_name` function, but everything else looks good to me. However, someone with more familiarity with the arrow adapter code should look over this as well.

2025-01-15 20:39 UTC, johnkerl requested changes
Thanks for working on this @XanthosXanthopoulos !

2025-01-15 20:39 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.cc
> -                std::to_string(lo),
I do seem to recall these were about crash avoidance on _some_ platform (I don't recall which). I'd rather leave these as-is please.

2025-01-15 20:39 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.cc
> +            });
This could be pulled out into a utility function

2025-01-15 20:39 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.cc
> +                "{} missing",
```suggestion
                "'{}' missing",
```

Strings in error messages should always be quoted/bracketed. Even if you think it's impossible for the string to ever be empty. Heaven forbid someday there is some bug somewhere somehow ... and an empty string gets in here ... that needs to be clear to everyone that sees the error message.

2025-01-15 20:39 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.cc
> +        if ((*column)->tiledb_dimensions().has_value()) {
This is a bit awkward.

* `column` needs to be `column_it` or some such -- it is _not_ a column, it is an iterator
* Then, const auto column = *column_it` after you check that `column _it != columns.end()`
* Then the rest of these `(*column)->foo` become `column->foo` as they should be

2025-01-15 20:39 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.cc
> +            std::vector<std::any> dom;
As on previous PRs: we cannot simply say `dom` or `domain`, ever.

There are four things it can mean:

* core domain (which is soma maxdomain)
* soma domain (which is core current domain)

The names are confusing (and too late to change), and confusion is too easy, and developer confusion is high-risk

2025-01-15 20:39 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.cc
> +            std::vector<std::any> dom;
Perhaps rename `dom` to `cdslot`

2025-01-15 20:39 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +    template <typename T, size_t Take, size_t Skip = 0>
Please state as a compact summary, right here as a code comment, what `Take` and `Skip` are for, what they do, and an example usage.

2025-01-17 18:56 UTC, johnkerl requested changes

2025-01-17 18:56 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * Complex column types are supported. The type for each sub column is an
```suggestion
     * Complex column types are supported. The type for each subcolumn is an
```

2025-01-17 18:56 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * Read a part of am Arrow array to an std::array and cast in to and
```suggestion
     * Read a part of an Arrow array to an std::array and cast in to an
```

2025-01-17 18:56 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * format casted as an std::any object. The std::array will skip 2 element
```suggestion
     * format casted as an std::any object. The std::array will skip 2 elements
```

2025-01-17 18:56 UTC, johnkerl commented on libtiledbsoma/test/unit_soma_column.cc
> +        // REQUIRE(str_external.second >= "~");
Please remove

2025-01-17 18:56 UTC, johnkerl commented on libtiledbsoma/src/utils/util.cc
> +std::shared_ptr<SOMAColumn> find_column_by_name(
Nice 😎

2025-01-17 18:56 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * @tparam Skip The number of elements to skip.
I was wondering why `Take` and `Skip` are template parameters and not simply function arguments. (The latter seems simpler.)

After having read through your code here, the answer seems to be: because you are constructing `std::array` objects (which are fixed-size) in various places, rather than `std::vector` (which are not fixed-size).

It's a good reason to have `Take` and `Skip` be implemented as template parameters, but I found it non-obvious.

Please come out and state this reasoning, right here, as a comment.

2025-01-17 19:17 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     */
@XanthosXanthopoulos to be clear, I'm not asking you to  use a different solution. I'm asking to be clear to the reader the (very good!) reasons you chose the solution you're using.

Please take both paragraphs you just wrote, and put them in the code as comments as well. They are _highly_ informative. :)

2025-01-17 20:13 UTC, jp-dark approved these changes
LGTM once the remaining change requests are addressed.

2025-01-21 00:18 UTC, XanthosXanthopoulos commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * @tparam Skip The number of elements to skip.
`Skip` wasn't required to be a template parameter, so I replaced it with just a function argument

2025-01-23 18:58 UTC, johnkerl requested changes
Thanks @XanthosXanthopoulos !! :) 

Mainly copy-editing mods here

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_column.cc
> +        // composite columns, thus the metadata are trivially contructuble
```suggestion
        // composite columns, thus the metadata are trivially constructible
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.cc
> +    // and NOT the arrow schema
```suggestion
    // and NOT the Arrow schema
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/common.h
> +const std::string TDB_SOMA_SCHEMA_COL_ATTR_KEY = "tiledb_attributes";
```suggestion
const std::string TILEDB_SOMA_SCHEMA_KEY = "tiledb_soma_schema";
const std::string TILEDB_SOMA_SCHEMA_VERSION = "0.0.1";
const std::string TILEDB_SOMA_SCHEMA_COL_KEY = "tiledb_columns";
const std::string TILEDB_SOMA_SCHEMA_COL_TYPE_KEY = "tiledb_column_type";
const std::string TILEDB_SOMA_SCHEMA_COL_DIM_KEY = "tiledb_dimensions";
const std::string TILEDB_SOMA_SCHEMA_COL_ATTR_KEY = "tiledb_attributes";
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * Return a copy of the data in a specified column of an arrow table.
```suggestion
     * Return a copy of the data in a specified column of an Arrow table.
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +                "fo bounds.");
```suggestion
                "ArrowAdapter::get_table_any_column_by_index: column index out "
                "of bounds.");
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * Read a part of am Arrow array to an std::array and cast in to an
```suggestion
     * Read a part of an Arrow array to an std::array and cast into an
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * elements as dictated by `offset` and copy the next 3 from the Arrow
```suggestion
     * elements as specified by `offset` and copy the next 3 from the Arrow
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * an leaf node with no subarrays.
```suggestion
     * a leaf node with no subarrays.
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * where the arrow array provided has 5 values per dimension and we only
```suggestion
     * where the Arrow array provided has 5 values per dimension and we only
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * `S` is required to be a template parameter to specify the compile time
```suggestion
     * `S` is required to be a template parameter to specify the compile-time
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/utils/arrow_adapter.h
> +     * different style.
```suggestion
     * dimension type. std::variant can provide all the above; this is a stylistic choice.
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_geometry_column.cc
> +            "Epected 1, got {}",
```suggestion
            "[SOMAGeometryColumn][deserialize] Invalid number of attributes: "
            "expected 1, got {}",
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_geometry_column.cc
> +            "Epected number divisible by 2, got {}",
```suggestion
            "[SOMAGeometryColumn][deserialize] Invalid number of dimensions: "
            "expected number divisible by 2, got {}",
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_dimension.cc
> +            "Epected 1, got {}",
```suggestion
            "[SOMADimension][deserialize] Invalid number of dimensions: "
            "expected 1, got {}",
```

2025-01-23 18:58 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_array.cc
> +        // Non geometry dataframes have trivially constructible columns and do
```suggestion
        // Non-geometry dataframes have trivially constructible columns and do
```

2025-01-23 20:29 UTC, johnkerl approved these changes
Thanks @XanthosXanthopoulos !! :)

2025-01-23 21:18 UTC, merged