SOMADimension, part 1
single-cell-data/TileDB-SOMA pull request #3425
Opened 2024-12-12 11:06 UTC by XanthosXanthopoulos

SOMAColumn provides an abstraction over TileDB attributes and dimensions and exposes a common interface for all columns regardless of type. Subclasses of SOMAColumn can implement complex indexing mechanism through additional dimensions and encapsulate all that logic in one place and make it modular.

Subsequent PRs will add implementation for dimension and attributes.

Throughout this PR there is extensive use of std::any to enable polymorphism with the different SOMAColumn types while maintaining a templated interface at the abstract SOMAColumn.

**Notes for Reviewer:**
This PR introduces the abstract SOMAColumn class and the SOMADimension concrete class with basic unit tests.

2024-12-12 14:21 UTC, johnkerl reviewed
I'm only partway through this PR. I'm still struggling with this (now) 1,875-line PR -- it's doing a lot of things. I'll need to pause and work on some other things for a while, and come back to this. (The other 3 PRs you split out that were smaller were nicely self-contained and self-descriptive and I was able to understand and review them earlier today.)

2024-12-12 14:21 UTC, johnkerl commented on libtiledbsoma/src/soma/soma_column.cc
> +        if (current_domain.first == "" && (current_domain.second == "\x7f" ||
There was a comment here about why both `\x7f` and `\xff` -- it needs to be retained. This is very confusing without that comment. (Which is why I put the comment in.)

https://github.com/single-cell-data/TileDB-SOMA/blob/a8349a5cdd295bdb04b965e3e91c3a8959e044e9/libtiledbsoma/src/soma/soma_array.h#L901-L920

2024-12-23 19:56 UTC, jp-dark requested changes
This looks good for the most part, but it's so big it's hard to follow everything. Let's do a code walk through together next time we are both working.

I also added a couple small comments, and John's comment about the missing code comments still needs to be addressed.

2024-12-23 19:56 UTC, jp-dark commented on libtiledbsoma/src/tiledbsoma/tiledbsoma
> +#include "soma/soma_dimension.h"
Looks like you remove these in a future PR. Might as well just not add them in to begin with.

2024-12-31 14:37 UTC, jp-dark commented on libtiledbsoma/src/soma/soma_dimension.h
> +    virtual inline std::string name() const override {
You should drop the `virtual` from these methods. See [ISO C++ Core Guidelines](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final) for an explanation.

2025-01-02 14:40 UTC, jp-dark approved these changes

2025-01-02 15:40 UTC, merged