[c++] Build libtiledbsoma static library
single-cell-data/TileDB-SOMA pull request #423
Opened 2022-10-17 18:33 UTC by gspowley

This PR adds a `libtiledbsoma` static library build to cmake. After running `scripts/bld`, the library can be found at `dist/lib/libtiledbsoma.a` at the top of the repo.

2022-10-17 18:54 UTC, eddelbuettel commented
Could you add a mode where it produces only `dist/lib/libtiledbsoma.a` but no cpython library and no catch2 binary?  When the R package builds in isolation it only needs that static library.

2022-10-18 21:05 UTC, johnkerl approved these changes

2022-10-18 21:17 UTC, eddelbuettel requested changes
The build should not require more resources or time than the narrow use it replaces so it would be desirable to a skip the build of test binary, and the build of the second shared library.

2022-11-01 20:50 UTC, gspowley commented
Closing in favor of #496.

2022-11-01 20:50 UTC, closed without merging