Support value-filter on boolean columns
single-cell-data/TileDB-SOMA pull request #579
Opened 2022-12-06 03:38 UTC by johnkerl

Needs unit-test

2022-12-06 23:24 UTC, gspowley requested changes

2022-12-06 23:24 UTC, gspowley commented on libtiledbsoma/test/test_query_condition.py
> +    assert len(pandas.index) == 342
We should compare the pandas query to the soma query:
```python
assert len(pandas.index) == soma_arrow.num_rows
```

2022-12-07 02:31 UTC, johnkerl commented
@gspowley ready for review round two! :)

2022-12-07 14:16 UTC, gspowley approved these changes
LGTM!

2022-12-07 17:12 UTC, merged